<a href="https://colab.research.google.com/github/pavankumarb26/ML-Concepts/blob/main/Handling_imbalance_data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Handling imbalance data set

In [1]:
import numpy as np
import pandas as pd

credit_card = pd.read_csv('/content/credit_data.csv')
credit_card.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [3]:
credit_card['Class'].value_counts()

Class
0.0    217520
1.0       403
Name: count, dtype: int64

This is highly unbalanced Data set

0 --> Legit Transactions
1 --> Fraudlent Transactions

In [4]:
legit = credit_card[credit_card.Class == 0]
fraud = credit_card[credit_card.Class == 1]

In [5]:
print(legit.shape)
print(fraud.shape)

(217520, 31)
(403, 31)

Build a sample data set containing Similar distribution of legit and fraudulent transaction

Under-sampling

In [8]:
legit_sample = legit.sample(n=403)

In [9]:
print(legit_sample.shape)

(403, 31)

Concatenate the two dataframes

In [13]:
new_dataset = pd.concat([legit_sample, fraud],axis = 0)

In [14]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
208389,137096.0,-0.572120,-0.936383,1.804381,-2.675887,-0.410749,0.160700,-0.448519,-0.074212,-2.128295,...,-0.412786,-0.734466,-0.094017,0.659843,0.249967,-0.433478,-0.291416,-0.258365,56.78,0.0
130312,79330.0,1.203226,0.134766,0.599447,0.562325,-0.610337,-0.808958,-0.104695,-0.015065,-0.078249,...,-0.204025,-0.675367,0.161656,0.503142,0.126661,0.067846,-0.039003,0.008694,1.29,0.0
96456,65775.0,-0.376701,1.062994,1.364912,-0.152744,0.204772,-0.603543,0.720916,-0.056455,-0.419391,...,-0.256484,-0.654935,-0.088668,-0.123395,-0.114678,0.100851,0.267239,0.116737,2.69,0.0
199876,133174.0,-0.276820,1.051726,-0.061365,-0.146551,1.114834,-1.257261,1.409898,-0.523847,-0.010386,...,-0.253853,-0.283012,-0.056694,-0.117805,0.128606,-0.410766,0.024483,-0.118234,7.70,0.0
66931,52283.0,-1.686335,0.646867,2.695738,0.901120,-1.869209,1.183325,-1.289603,0.024953,0.395570,...,0.232317,-0.522137,-0.047881,0.351416,0.254371,-0.075627,0.422070,0.008594,25.00,0.0

In [17]:
new_dataset.shape
new_dataset['Class'].value_counts()

Class
0.0    403
1.0    403
Name: count, dtype: int64